/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  ignoredRouteFiles: ['**/.*'],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "build/index.js",
  // publicPath: "/build/",
  serverDependenciesToBundle: [
    /^remark*/,
    /^rehype.*/,
    /^unified.*/,
    /^micromark.*/,
    /^mdast.*/,
    /^react-querybuilder.*/,
    /^react-day-picker.*/,
    /^react-dnd-html5-backend.*/,
    /^dnd-core.*/,
    /^@react-dnd.*/,
    /^@udecode\/plate-ui-dnd.*/,
    /^@udecode\/plate.*/,
    /^@udecode\/plate-serializer-md.*/,
    /^decode-named-character-reference.*/,
    /^character-entities.*/,
    /^unist-util-stringify-position.*/,
    /^character-reference-invalid.*/,
    /^is-*/,
    /^copy-to-clipboard.*/,
    /^unist-.*/,
    /^hast-*/,
    /^property-information.*/,
    /^hast-util-whitespace.*/,
    /^space-separated-tokens.*/,
    /^comma-separated-tokens.*/,
    /^zen-observable-ts.*/,
    /^ts-invariant.*/,
    /^zen-observable-ts.*/,
    /^is-alphabetical.*/,
    /^@sindresorhus\/slugify.*/,
    /^react-markdown.*/,
    /^micromark-util-symbol.*/,
    /^zwitch.*/,
    /^bail.*/,
    /^trough.*/,
    /^fault.*/,
    /^ccount.*/,
    /^react-dnd.*/,
    /^parse-entities.*/,
    /^stringify-entities.*/,
    /^hastscript.*/,
    /^ts-invariant.*/,
    /^unist-util-map.*/,
    /^markdown-table.*/,
    /^longest-streak.*/,
    /^vfile.*/,
    /^vfile-message.*/,
    /^@apollo\/client.*/,
    /^html-.*/,
    /^trim-.*/,
    /^@sindresorhus\/*/
  ]
}
